services:
  - type: web
    name: career-match-api
    runtime: docker
    plan: free
    dockerfilePath: ./backend/Dockerfile
    dockerContext: .
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: SECRET_KEY
        value: uEC6dodPtE7F9Cu0SLn4CWhKlLRDcsb60DonlhAaUGo
      - key: DEBUG
        value: "false"
      - key: APP_NAME
        value: Career Match API
      - key: APP_VERSION
        value: "1.0.0"
      - key: CORS_ORIGINS
        value: '["https://cv-match-engine.vercel.app", "https://*.onrender.com"]'
